### ISSUE TITLE
Add simple example script

### ISSUE THREAD

**Issue by BlackEdder** [Abscissa/scriptlike#17]
It might be useful to add a basic example of how to use this in a script. For example I used 

```
dub fetch scriptlike
```

and then you can build an executable script like so:

```{D}
#!/usr/bin/rdmd -I/path/to/home/.dub/packages/scriptlike-0.9.2/src/
import scriptlike;

void main()
{
    "Hello world!".writeln;
}
```

You of course need to make it executable as well
```
chmod +x myscript.d
./myscript.d
```

**Comment by adamryczkowski** [comment]
That works very well.

**Comment by Abscissa** [comment]
Now added as of v0.9.4:

https://github.com/Abscissa/scriptlike/blob/master/USAGE.md
