### ISSUE TITLE
Documentation: Lack of usage patterns, example scripts, and user documentation.

### ISSUE THREAD

**Issue by adamryczkowski** [Abscissa/scriptlike#20]
I know, that that can be inferred from the unittests, but it is time consuming: they are scattered throughout the code and not necessarily examples of typical/intended usage patterns. 

Could you write some simple D scripts as examples of the intended usage?

------

Sometimes, great applications start as a shell script. And D is a perfect language to let the shell script evolve into something big and complex. I wish, that the authors of Puppet Configuration Management had started writing it in D...

**Comment by Abscissa** [comment]
Now added to homepage/readme as of v0.9.4:

https://github.com/Abscissa/scriptlike
