### ISSUE TITLE
Unable to build docs of own project with DUB

### ISSUE THREAD

**Issue by JesseKPhillips** [Abscissa/scriptlike#34]
When attempting to use $ dub build --build=docs on a project which depends on scriptlike, the compiler errors with

package.d(45,24): Error: module changelog is in file 'changelog.d' which can not be read

This is probably more an issue with DUB, but maybe a different choice could be made within scriptlike for its doc generation.

**Comment by Abscissa** [comment]
'Twas my fault. I had that file's import under a `version(D_Ddoc)`, which of course is going to be defined for other projects too. And `changelog.d` was deliberately in a separate directory from the main scriptlike sources. Fixed now.

**Comment by JesseKPhillips** [comment]
Thanks would be good to have a minor version bump to use it from DUB.

**Comment by Abscissa** [comment]
On 03/03/2017 03:08 PM, Jesse Phillips wrote:
> Thanks would be good to have a minor version bump to use it from DUB.
>

Yea, on the way. I'm actually taking this as an excuse to toss in a few 
other quick things I've been meaning to. New release within the next 
couple hours...

**Comment by Abscissa** [comment]
Done. Tagged v0.10.2
